### ISSUE TITLE
Territory list should be in alphabetical order

### ISSUE THREAD

**Issue by fjlopez** [sitmun/sitmun-backend-core#177]
#### Is your feature request related to a problem? Please describe.
This feature request addresses a usability issue faced by stakeholders in the [SITMUN Viewer App](https://github.com/sitmun/sitmun-viewer-app) where territories available for an application are displayed to users. The core of the problem lies in the unsorted presentation of territories, which can lead to user frustration when attempting to locate specific territories within the list.

![Image](https://github.com/sitmun/sitmun-backend-core/assets/3294927/5410b7bf-d2a2-4a87-b530-4638d5420b08)

Currently, the application fetches a list of territories via the API endpoint `/api/config/client/application/{appId}/territories`. However, this list is not presented in a specific order. Stakeholders expect that when territories are displayed, they should be listed in alphabetical order by their names (labels). This ordered listing would enable users to find the desired territories more swiftly and intuitively.
#### Describe the solution you'd like
The requested feature entails modifying the backend logic associated with the `/api/config/client/application/{appId}/territories` API endpoint. Specifically, the change would ensure that the list of territories returned by this endpoint is sorted in ascending alphabetical order by the territory name. 
#### Describe alternatives you've considered
An alternative solution involves implementing the sorting feature within the map client, as suggested in [a related issue](https://github.com/sitmun/sitmun-viewer-app/issues/23). While this approach could address the sorting issue, it places the responsibility on the client side, potentially leading to inconsistencies across different clients or additional processing overhead on the client devices. Opting to implement the sorting at the API level offers a more centralized and efficient solution, ensuring consistency and reducing the complexity on the client side.

**Comment by fjlopez** [comment]
Fixed in https://github.com/sitmun/sitmun-backend-core/commit/1fcc35119acd80acc4f9f506c950550e3107935a

**Comment by codinachssm** [comment]
OK with the ordered list of territories after selecting an app.
But the initial list of territories before selecting any app is still not in alphabetical order.
Do you think this case should not be in alphabetical order? What do you think?

![image](https://github.com/sitmun/sitmun-backend-core/assets/38311286/e6d68ff1-4a78-4981-b916-5fb523c34845)

**Comment by fjlopez** [comment]
Done. I did a quick fix and implemented your proposal https://github.com/sitmun/sitmun-backend-core/commit/63d849ed198f3c8d1ac4d7ac84cedb924f0db92d

Could you review it? I think that all the cases related to territories are now sorted.

**Comment by codinachssm** [comment]
Perfecte! Thanks!
